type: systemd
system:
  enabled:
    - tailscaled.service
#    - com.system76.Scheduler.service
#    - libvirtd.service
#    - cockpit.socket
#    - sshd
#    - virtxend.service
#    - virtxend.socket