[customizations.installer.kickstart]
contents = """
# --- Locale & input (prevents the UTF-8 crash) ---
lang en_US.UTF-8
keyboard us

# --- Timezone & time sync (Vancouver, with NTP) ---
timezone America/Vancouver --utc
timesource --ntp-server=0.pool.ntp.org --ntp-server=1.pool.ntp.org
services --enabled=chronyd

# --- Networking (DHCP up front so logs/remote work) ---
network --bootproto=dhcp --device=link --activate

# --- Installer UI so you can choose the target disk ---
# Use 'text' for a reliable TTY experience in Nutanix console.
# (Swap to 'graphical' if you prefer the GUI/VNC flow.)
text
interactive

# No storage directives here on purpose:
# leaving out clearpart/autopart forces the STORAGE screen and lets you pick the drive.

# --- Finish up normally ---
reboot
"""