[customizations.installer.kickstart]
contents = """
# --- Locale & input (prevents your UTF-8 crash) ---
lang en_US.UTF-8
keyboard us
timezone Etc/UTC --utc

# --- Bring up basic networking (optional but handy for logs/remote) ---
network --bootproto=dhcp --device=link --activate

# --- Make the installer UI appear so you can pick the disk ---
# Use text UI by default (works in a serial/virt console); remove 'text' and use 'graphical' if you prefer VNC.
text
interactive

# IMPORTANT:
# Do NOT include 'clearpart' or 'autopart' here.
# With no storage directives, Anaconda will stop on the STORAGE spoke
# and let you choose the disk and (auto) partitioning, then continue.

# --- Finish up normally ---
reboot
"""

