name: bootc-builder
on:
  schedule:
    - cron:
        "00 06 * * *" # build at 06:00 UTC every day
        # (20 minutes after last ublue images start building)
  push:
    paths-ignore: # don't rebuild if only documentation has changed
      - "**.md"

  pull_request:
  workflow_dispatch: # allow manually triggering builds
concurrency:
  # only run one build at a time
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  workstation10:
    name: EL10 Workstation
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        recipe:
          - /EL10/alma/alma10-workstation.yml
          - /EL10/alma/alma10-workstation-nvidia.yml
    steps:
      # the build is fully handled by the reusable github action
      - name: EL10 Workstation
        uses: blue-build/github-action@v1.9
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          rechunk: true
          maximize_build_space: true

  server10:
    name: EL10 Server
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        recipe:
          - /EL10/alma/alma10-server.yml
          - /EL10/alma/alma10-server-nvidia.yml
    steps:
      # the build is fully handled by the reusable github action
      - name: EL10 Server
        uses: blue-build/github-action@v1.9
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          rechunk: true
          maximize_build_space: true

  workstation9:
    name: EL9 Workstation
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        recipe:
          - /EL9/alma/alma9-workstation.yml
          - /EL9/alma/alma9-workstation-nvidia.yml
    steps:
      # the build is fully handled by the reusable github action
      - name: EL9 Workstation
        uses: blue-build/github-action@v1.9
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          rechunk: true
          maximize_build_space: true

  server9:
    name: EL9 Server
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        recipe:
          - /EL9/alma/alma9-server.yml
          - /EL9/alma/alma9-server-nvidia.yml
    steps:
      # the build is fully handled by the reusable github action
      - name: EL9 Server
        uses: blue-build/github-action@v1.9
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          rechunk: true
          maximize_build_space: true

  workstation42:
    name: Fedora Workstation
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        recipe:
          - /fedora/42/fedora42-workstation.yml
          - /fedora/42/fedora42-workstation-nvidia.yml
    steps:
      # the build is fully handled by the reusable github action
      - name: Fedora 42 Workstation
        uses: blue-build/github-action@v1.9
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          rechunk: true
          maximize_build_space: true

  server42:
    name: Fedora Server
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        recipe:
          - /fedora/42/fedora42-server.yml
          - /fedora/42/fedora42-server-nvidia.yml
    steps:
      # the build is fully handled by the reusable github action
      - name: Fedora 42 Server
        uses: blue-build/github-action@v1.9
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          rechunk: true
          maximize_build_space: true